"""add something new

Revision ID: 2a4de3e33320
Revises: 
Create Date: 2025-04-21 12:24:17.899107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4de3e33320'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_access_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('access_point_id', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('privacy', sa.String(length=64), nullable=True),
    sa.Column('cipher', sa.String(length=64), nullable=True),
    sa.Column('authentication', sa.String(length=64), nullable=True),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('beacons', sa.Integer(), nullable=False),
    sa.Column('iv', sa.Integer(), nullable=False),
    sa.Column('lan_ip', sa.String(length=45), nullable=True),
    sa.Column('id_length', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('packets', sa.Integer(), nullable=False),
    sa.Column('bssid', sa.String(length=17), nullable=True),
    sa.Column('probed_essids', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_stations')
    op.drop_table('scan_access_points')
    # ### end Alembic commands ###
