"""add scan_id to access_point table

Revision ID: 5a26101ddbc4
Revises: 5c4bc347a112
Create Date: 2025-04-24 09:40:47.509700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a26101ddbc4'
down_revision = '5c4bc347a112'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        # Step 1: Spalte existiert bereits, also keine neue Spalte anlegen
        batch_op.alter_column('scan_id', existing_type=sa.Integer(), nullable=True)

        # Step 2: Foreign Key erst hinzufügen, wenn Daten sauber sind
        batch_op.create_foreign_key(
            'fk_access_points_scan_id_scans',
            'scans',
            ['scan_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('scan_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
