"""change to mysql

Revision ID: 91b18243d851
Revises: 
Create Date: 2025-04-26 21:11:44.027558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b18243d851'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('is_camera', sa.Boolean(), nullable=False))

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('is_camera', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_column('is_camera')
        batch_op.drop_column('manufacturer')

    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.drop_column('is_camera')
        batch_op.drop_column('manufacturer')

    # ### end Alembic commands ###
