"""add handshake to databasese

Revision ID: a197d660c3fd
Revises: 15708a5d4d75
Create Date: 2025-05-02 19:13:12.568110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a197d660c3fd'
down_revision = '15708a5d4d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handshake_file', sa.String(length=256), nullable=True))

    with op.batch_alter_table('deauth_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handshake_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deauth_actions', schema=None) as batch_op:
        batch_op.drop_column('handshake_file')

    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.drop_column('handshake_file')

    # ### end Alembic commands ###
