"""fix dependencies

Revision ID: b7eeed833870
Revises: 6d0d418865a0
Create Date: 2025-05-04 19:11:09.754674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7eeed833870'
down_revision = '6d0d418865a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_access_points', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scan_access_points_access_point_id_access_points', type_='foreignkey')
        batch_op.drop_constraint('fk_scan_access_points_scan_id_scans', type_='foreignkey')
        batch_op.create_foreign_key(None, 'access_points', ['access_point_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'scans', ['scan_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('scan_stations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scan_stations_scan_id_scans', type_='foreignkey')
        batch_op.drop_constraint('fk_scan_stations_station_id_stations', type_='foreignkey')
        batch_op.create_foreign_key(None, 'stations', ['station_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'scans', ['scan_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('scan_stations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_scan_stations_station_id_stations', 'stations', ['station_id'], ['id'])
        batch_op.create_foreign_key('fk_scan_stations_scan_id_scans', 'scans', ['scan_id'], ['id'])

    with op.batch_alter_table('scan_access_points', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_scan_access_points_scan_id_scans', 'scans', ['scan_id'], ['id'])
        batch_op.create_foreign_key('fk_scan_access_points_access_point_id_access_points', 'access_points', ['access_point_id'], ['id'])

    # ### end Alembic commands ###
