"""add filename to scan, counter + cracked_password to access point

Revision ID: d4b0b0689f1d
Revises: 2a4de3e33320
Create Date: 2025-04-23 18:48:26.821404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b0b0689f1d'
down_revision = '2a4de3e33320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counter', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cracked_password', sa.String(length=128), nullable=True))

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('filename')

    with op.batch_alter_table('access_points', schema=None) as batch_op:
        batch_op.drop_column('cracked_password')
        batch_op.drop_column('counter')

    # ### end Alembic commands ###
